### ISSUE TITLE
Step doesn't bind if quotes are used around parameters in step definition

### ISSUE THREAD

**Issue by McCraigJ** [autostep/autostep#31]
If I create a step definition that has quotes around parameters, then the step doesn't bind.
E.g. 
**Step Definition**
```gherkin
Step: Given I have logged in to my app as '{username}', password '{pwd}'
```
**Usage**
```gherkin
Given I have logged in to my app as 'USER', password 'PWD'
```
**Result**
The Given in the usage shows a linker error

**Comment by alistairjevans** [comment]
The reason it doesn't parse is that because the opening quote has already been consumed as part of a `Word`, the end quote is considered part of the argument, so the following quote in the original step definition doesn't match.

The best way to resolve this is to indicate that the step definition is not good (because you don't need quotes round the argument, and it looks weird). The fix will be to raise an error on the definition.
